version: '3.8'

services:
  mars-eureka-server:
    container_name: mars-eureka-server
    image: mars-eureka-server:latest
    build:
      context: ./Inl채mning/Mars-Server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  mars-eureka-gateway:
    container_name: mars-eureka-gateway
    image: mars-eureka-gateway:latest
    build:
      context: ./Inl채mning/Mars-gateway
      dockerfile: Dockerfile
    ports:
      - "8585:8585"
    networks:
      - mynetwork
    depends_on:
      - mars-eureka-server

  mars-eureka-main-api:
    container_name: mars-eureka-main-api
    image: mars-eureka-main-api:latest
    build:
      context: ./Inl채mning/Wigell-Travels
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/wigellsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "7070:7070"
    networks:
      - mynetwork
    depends_on:
      - mars-eureka-server

  mars-eureka-support-api:
    container_name: mars-eureka-support-api
    image: mars-eureka-support-api:latest
    build:
      context: ./Inl채mning/ChangeValue
      dockerfile: Dockerfile
    ports:
      - "5656:5656"
    networks:
      - mynetwork
    depends_on:
      - mars-eureka-main-api
      - mars-eureka-server

networks:
  mynetwork:
    driver: bridge
