server:
  port: 8585
spring:
  application:
    name: Mars-Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: WIGELL-TRAVELS
            uri: lb://WIGELL-TRAVELS
            predicates:
              - Path=/api/v2/**